### ISSUE TITLE
Getting StackOverflowError in regular usage

### ISSUE THREAD

**Issue by amaltson** [vrapper/vrapper#304]
Today I started getting `StackOverflowError`s in Eclipse. I took a look at the `.log` file in the workspace's `.metadata` and it looks like the SOE is being caused by Vrapper. I have Vrapper Unstable 0.35.201308271 installed.

I just updated to Vrapper Unstable 0.35.201309082, I'll post back how the new version is going.

One thing that's different about my Eclipse today is that I've just installed [Infinitest](http://infinitest.github.io/), not sure if there's anyway the two could conflict with each other, seems unlikely.

Here's the StackOverflowError stacktrace:

```
!ENTRY org.eclipse.ui 4 0 2013-09-09 21:18:38.470
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.StackOverflowError
    at java.util.HashMap.get(HashMap.java:300)
    at net.sourceforge.vrapper.keymap.HashMapState.press(HashMapState.java:33)
    at net.sourceforge.vrapper.keymap.UnionState.press(UnionState.java:17)
    at net.sourceforge.vrapper.keymap.UnionState.press(UnionState.java:17)
    at net.sourceforge.vrapper.keymap.UnionState.press(UnionState.java:17)
    at net.sourceforge.vrapper.keymap.UnionState.press(UnionState.java:17)
    at net.sourceforge.vrapper.keymap.UnionState.press(UnionState.java:17)
    at net.sourceforge.vrapper.keymap.UnionState.press(UnionState.java:17)
    at net.sourceforge.vrapper.keymap.UnionState.press(UnionState.java:17)
    at net.sourceforge.vrapper.keymap.UnionState.press(UnionState.java:17)
    at net.sourceforge.vrapper.keymap.UnionState.press(UnionState.java:17)
    at net.sourceforge.vrapper.keymap.UnionState.press(UnionState.java:17)
    at net.sourceforge.vrapper.keymap.UnionState.press(UnionState.java:17)
    at net.sourceforge.vrapper.keymap.UnionState.press(UnionState.java:17)
    at net.sourceforge.vrapper.keymap.UnionState.press(UnionState.java:17)
    at net.sourceforge.vrapper.keymap.UnionState.press(UnionState.java:17)
    at net.sourceforge.vrapper.keymap.WrappingState.press(WrappingState.java:33)
    at net.sourceforge.vrapper.keymap.vim.RegisterState.press(RegisterState.java:25)
    at net.sourceforge.vrapper.vim.modes.CommandBasedMode.handleKey(CommandBasedMode.java:256)
    at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey0(DefaultEditorAdaptor.java:542)
    at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:339)
    at net.sourceforge.vrapper.vim.MacroPlayer.play(MacroPlayer.java:59)
    at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:345)
    at net.sourceforge.vrapper.vim.MacroPlayer.play(MacroPlayer.java:59)
    at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:345)
    at net.sourceforge.vrapper.vim.MacroPlayer.play(MacroPlayer.java:59)
    at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:345)
    at net.sourceforge.vrapper.vim.MacroPlayer.play(MacroPlayer.java:59)
    at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:345)

.... <more of the same>
```

**Comment by elicoten** [comment]
I had a similar problem and updating to the latest Vrapper Unstable solved the problem for me, however I'm not sure if it was specifically the new version of Vrapper that solved the problem or whether it was simply running through the installation procedure for Vrapper - perhaps uninstalling and re-installing the current version would also have worked.

The problem was triggered after attempting to install the Eclipse Dynamic Languages Toolkit for  Javascript.

**Comment by keforbes** [comment]
@elicoten, yeah it wasn't just you.  I [noticed it](https://github.com/vrapper/vrapper/issues/797#issuecomment-335677029) after testing one of the changes for @albertdev but he was able to hack together a solution.  Glad to hear the new version worked for you though. 😄

**Comment by albertdev** [comment]
@elicoten You would do me a favour if you could grab the full stacktrace of that error and paste it in a Github gist or upload to pastebin, just to confirm that you were suffering from the same error @keforbes is talking about.

Also, I'll have you know that my change is a proper solution and not a simple hack ;) (though I must admit that the code it is in deserves its "evil" nickname).

**Comment by elicoten** [comment]
@albertdev Here you go: https://pastebin.com/iekbfHBN
Hope that's useful

**Comment by albertdev** [comment]
@elicoten As we suspected that error was an issue which only existed on the unstable site for a few weeks, this means that we can keep this issue closed as it won't be a problem in a release version.

Thanks for your concern and your help in troubleshooting the problem. Feel free to open a new issue if you would encounter any new problems.
