### ISSUE TITLE
NullPointerException when editing java files

### ISSUE THREAD

**Issue by buesing** [vrapper/vrapper#596]
As soon as I open a java file in Eclipse, I get a NPE. When I click on ok, a new one shows up immediately. This makes the plugin unusable for me, rendering Eclipse unusable as well because I can't use vim shortcuts. This always happens with .java files, but sometimes also with .xml files.

Here is the stacktrace:
```
    java.lang.NullPointerException
        at net.sourceforge.vrapper.eclipse.platform.EclipseBufferAndTabService.setCurrentEditor(EclipseBufferAndTabService.java:87)
        at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.partActivated(InputInterceptorManager.java:313)
        at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.partActivated(InputInterceptorManager.java:340)
        at org.eclipse.ui.internal.PartService$6.run(PartService.java:149)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.PartService.partActivated(PartService.java:146)
        at org.eclipse.ui.internal.WorkbenchPage$17.run(WorkbenchPage.java:4870)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4867)
        at org.eclipse.ui.internal.WorkbenchPage.access$18(WorkbenchPage.java:4846)
        at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:210)
        at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:236)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
        at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:233)
        at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:684)
        at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:615)
        at org.eclipse.e4.ui.internal.workbench.swt.AbstractPartRenderer.activate(AbstractPartRenderer.java:106)
        at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer$1.handleEvent(ContributedPartRenderer.java:61)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4454)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1388)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1412)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1397)
        at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1718)
        at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1681)
        at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:3904)
        at org.eclipse.swt.widgets.Control.gtk_event_after(Control.java:3146)
        at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2084)
        at org.eclipse.swt.widgets.Control.windowProc(Control.java:5513)
        at org.eclipse.swt.widgets.Display.windowProc(Display.java:4668)
        at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
        at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9106)
        at org.eclipse.swt.widgets.Display.eventProc(Display.java:1253)
        at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
        at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2477)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3407)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```
Session data:
eclipse.buildId=4.4.1.M20140925-0400
java.version=1.8.0_31
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_AT
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

**Comment by buesing** [comment]
I'm in Debian Wheezy btw.

**Comment by albertdev** [comment]
Ouch, that looks like quite the stacktrace which likely means I forgot some null check somewhere. Sorry.

I haven't had it happen using Eclipse 4.4.0 and `org.eclipse.epp.package.jee.product` on XUbuntu 14.0.4, so maybe there's still some difference between the Java and EE editions. I'll try to reproduce it using a new Eclipse version for Java development.

**Comment by albertdev** [comment]
@buesing 
Could you close all editors and restart the workbench? It is possible that some editor like a manifest or Maven POM editor brought Vrapper in a bad state after which all opened editors will fail.

I'm not saying I won't need to fix this, but if this scenario holds I might know better what to look for. If you know that you e.g. opened some editor with multiple sub-pages, please tell me.

**Comment by buesing** [comment]
Didn't help, problem still persists. What I noticed now is that it doesn't happen right after I start eclipse, but only after I switch tabs a couple times. Then, as soon as I open a tab with a .java file, I get the exception. Maybe this helps.

**Comment by albertdev** [comment]
That does somewhat explain why I might not have seen it.

You say you trigger the problem when you switch to a .java file so what kind file were you editing before: plain XML, Maven POM files, Text files, Android files, something you installed a plugin for, ...?

**Comment by buesing** [comment]
Oh, I just noticed it only happens after I edit an android layout xml file,
like "activity_main.xml". They have an interface with a drag & drop screen.
I guess this screen causes it. I think it comes with ADT.

On Thu, Feb 12, 2015 at 4:07 PM, Bert Jacobs <notifications@github.com>
wrote:

> That does somewhat explain why I might not have seen it.
>
> You say you trigger the problem when you switch to a .java file so what
> kind file were you editing before: plain XML, Maven POM files, Text files,
> Android files, something you installed a plugin for, ...?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vrapper/vrapper/issues/596#issuecomment-74085505>.
>



-- 
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v.1.20130627

xo0EUc2rCwED/2xIG3E8yjtO6StBi/o8jaEAMe+etC9CWHNs8vDolNNPOucG
3UzjBTimn/NtR4Mie80lnUZjMCGuN9Kg6ICuSDHs0T33xsM/avFa77Vd1hSy
TefSWX1mHmhE8nOxl2jkEYNGWLeqBBXZxD5XiR9VlrF6ke1Ke06KHG+4hGC5
1XW9ABEBAAHNKU1vcml6IELDg8K8c2luZyA8bW9yaXouYnVlc2luZ0BnbWFp
bC5jb20+wpwEEAEIABAFAlHNqwwJENrKzUkubOOWAADATgP9FoSJhqbWs1Bp
/GuGlW0UnQunLMlmRVO65Nh4Q/kfjN8ETKfa7pCkM/p2WOkaOiZQDbqtAtHg
wUuWWc0ukQdq7Y0VU5Tsp6ZsetOoO38FRYTsRmW11dJaziA9mKMMNj0LeS7S
rb/Q2djLUSgvM1tbZPz+f4hafNlYk0uIYu4/4jo=
=nXjK

-----END PGP PUBLIC KEY BLOCK-----

**Comment by albertdev** [comment]
Thanks for pointing out that it was the ADT editor! This wasn't clear from your original report, and now I was able to reproduce it after installing the Android SDK (I didn't expect it would take up 13 GB).

I had not seen such an editor before and didn't account for the fact that a certain property returns null. Checking for that case immediately fixes the issue.

This will be included in the next release and unstable build.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.53.20150214) which includes this fix.  Please give it a try and let us know if you have any other problems.  Thanks!

**Comment by buesing** [comment]
This fixed it, thanks for the fast response!

**Comment by konata** [comment]
the same problem, thx for fixing this, the unstable update works!
