### ISSUE TITLE
AssertionError in Configuration$Option.globalStringSet

### ISSUE THREAD

**Issue by smelc** [vrapper/vrapper#642]
I'm hitting the stack trace below with vrapper 0.52.1 when I launch a (plugin-augmented) instance of Eclipse from my development Eclipse (I do that because in my company we develop Eclipse plugins). I've used vrapper (thank god for its existence!) for a number of years and this bug appeared when I updated to 0.52.1 (I believe I was using 0.35 before). It does not stop Eclipse from launching but vrapper is disabled.

I tried updating to 0.54, but I'm not sure I succeeded. The plugin-augmented Eclipse inherits vrapper from my development Eclipse (which has 0.54) but it is still showing 0.52.1 as the version (although I don't know how it's possible since there are no more 0.52 jars on my disk). I guess it's just an artifact that vrapper crashes because of the assertion failure, so my guess is that I'm hitting this bug also with 0.54.

I'm available to do further tests and/or try patches, since it should be easy for me to launch a development-version of vrapper.

Here's the trace:

~~~~~
Thread [main] (Suspended (exception AssertionError))	
	owns: RunnableLock  (id=100)	
	Configuration$Option<T>.globalStringSet(String, String, String, String...) line: 120	
	Options.<clinit>() line: 70	
	CommandLineParser.buildConfigEvaluator(boolean) line: 489	
	CommandLineParser.coreCommands() line: 378	
	CommandLineMode.<clinit>() line: 10	
	DefaultEditorAdaptor.__set_modes(DefaultEditorAdaptor) line: 204	
	DefaultEditorAdaptor.<init>(Platform, RegisterManager, boolean) line: 156	
	VimInputInterceptorFactory.createInterceptor(AbstractTextEditor, ITextViewer, BufferAndTabService) line: 126	
	InputInterceptorManager.interceptAbstractTextEditor(AbstractTextEditor) line: 175	
	InputInterceptorManager.interceptWorkbenchPart(IWorkbenchPart, NestedEditorPartInfo) line: 117	
	VrapperPlugin.restoreVimEmulationInActiveEditors() line: 121	
	VrapperStartup$1.run() line: 13	
	RunnableLock.run() line: 35	
	UISynchronizer(Synchronizer).runAsyncMessages(boolean) line: 136	
	Display.runAsyncMessages(boolean) line: 3774	
	Display.readAndDispatch() line: 3412	
	PartRenderingEngine$9.run() line: 1151	
	Realm.runWithDefault(Realm, Runnable) line: 332	
	PartRenderingEngine.run(MApplicationElement, IEclipseContext) line: 1032	
	E4Workbench.createAndRunUI(MApplicationElement) line: 148	
	Workbench$5.run() line: 636	
	Realm.runWithDefault(Realm, Runnable) line: 332	
	Workbench.createAndRunWorkbench(Display, WorkbenchAdvisor) line: 579	
	PlatformUI.createAndRunWorkbench(Display, WorkbenchAdvisor) line: 150	
	IDEApplication.start(IApplicationContext) line: 135	
	EclipseAppHandle.run(Object) line: 196	
	EclipseAppLauncher.runApplication(Object) line: 134	
	EclipseAppLauncher.start(Object) line: 104	
	EclipseStarter.run(Object) line: 380	
	EclipseStarter.run(String[], Runnable) line: 235	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 483	
	Main.invokeFramework(String[], URL[]) line: 648	
	Main.basicRun(String[]) line: 603	
	Main.run(String[]) line: 1465	
	Main.main(String[]) line: 1438	
~~~~~

**Comment by albertdev** [comment]
It's weird that you post a stacktrace without Fully Qualified Class Names, but I do recognize those names. I completely forgot that Vrapper uses assertions in some rare spots and hardly ever test with them enabled.

That does look like a programming bug, most likely some default option is configured incorrectly. This should be fixed by the next release, which will likely be either on the 1st of June or on the 8th.

With regards to the version mixup: do you have the Equinox OSGi console enabled in your "augmented Eclipse"? Can you try `ss vrapper` in there to list the versions?
Also note that some jars might be cached in your "Augmented Eclipse's" workspace, so worst case you might need to delete / reset it if possible (**NOTE** you do lose your test projects, files and settings that way).

**Comment by smelc** [comment]
Thank you for your quick feedback.

The trace wasn't fully qualified, because I copied it from Eclipse' debugger, not from the console. For the record, here's the trace that makes it to the console:

~~~~~
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.AssertionError)
	at org.eclipse.swt.SWT.error(SWT.java:4441)
	at org.eclipse.swt.SWT.error(SWT.java:4356)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:139)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3774)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3412)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.AssertionError
	at net.sourceforge.vrapper.platform.Configuration$Option.globalStringSet(Configuration.java:120)
	at net.sourceforge.vrapper.vim.Options.<clinit>(Options.java:70)
	at net.sourceforge.vrapper.vim.modes.commandline.CommandLineParser.buildConfigEvaluator(CommandLineParser.java:489)
	at net.sourceforge.vrapper.vim.modes.commandline.CommandLineParser.coreCommands(CommandLineParser.java:378)
	at net.sourceforge.vrapper.vim.modes.commandline.CommandLineMode.<clinit>(CommandLineMode.java:10)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.__set_modes(DefaultEditorAdaptor.java:204)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.<init>(DefaultEditorAdaptor.java:156)
	at net.sourceforge.vrapper.eclipse.interceptor.VimInputInterceptorFactory.createInterceptor(VimInputInterceptorFactory.java:126)
	at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.interceptAbstractTextEditor(InputInterceptorManager.java:175)
	at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.interceptWorkbenchPart(InputInterceptorManager.java:117)
	at net.sourceforge.vrapper.eclipse.activator.VrapperPlugin.restoreVimEmulationInActiveEditors(VrapperPlugin.java:121)
	at net.sourceforge.vrapper.eclipse.activator.VrapperStartup$1.run(VrapperStartup.java:13)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
~~~~~

Here's the output of `ss vrapper`:

~~~~~
osgi> ss vrapper
"Framework is launched."


id	State       Bundle
1300	RESOLVED    net.sourceforge.vrapper.core_0.54.0
1301	ACTIVE      net.sourceforge.vrapper.eclipse_0.54.0
~~~~~

I'm hence running the 0.54 version despite _Installation Details_ tells 0.52.1 :-/

I'll keep you posted when I try the upcoming version containing your fix.

**Comment by albertdev** [comment]
I committed a fix which will be included in the next unstable and release build. Thanks for filing this report, I will try to check the assertions from now on.

**Comment by smelc** [comment]
I confirm that I'm not hitting this bug anymore with version 0.56. Thank you.
