### ISSUE TITLE
net.sourceforge.vrapper.platform.VrapperPlatformException after 'o' on last line of file

### ISSUE THREAD

**Issue by smelc** [vrapper/vrapper#652]
I hit the stacktrace below when pressing 'o' (in command mode) on the last line of a java file, using vrapper 0.56. The last line is like this (space matters):

~~~~
   }
~~~~

When I do 'o', the cursor moves as follows:

~~~~
   }
     | <- the cursor
~~~~

Then if I go back into command mode by pressing ESC, I get:

~~~~
net.sourceforge.vrapper.platform.VrapperPlatformException: Failed to set mark for M 25706
	at net.sourceforge.vrapper.eclipse.platform.EclipseCursorAndSelection.setMark(EclipseCursorAndSelection.java:520)
	at net.sourceforge.vrapper.vim.modes.InsertMode.saveTypedText(InsertMode.java:253)
	at net.sourceforge.vrapper.vim.modes.InsertMode.leaveMode(InsertMode.java:194)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.changeMode(DefaultEditorAdaptor.java:373)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.changeModeSafely(DefaultEditorAdaptor.java:218)
	at net.sourceforge.vrapper.vim.modes.InsertMode.handleKey(InsertMode.java:336)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey0(DefaultEditorAdaptor.java:667)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:404)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey(DefaultEditorAdaptor.java:399)
	at net.sourceforge.vrapper.eclipse.interceptor.VimInputInterceptorFactory$VimInputInterceptor.verifyKey(VimInputInterceptorFactory.java:188)
	at org.eclipse.jface.text.TextViewer$VerifyKeyListenersManager.verifyKey(TextViewer.java:492)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:66)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4454)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1388)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1412)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1397)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1182)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:5981)
	at org.eclipse.swt.custom.StyledText$7.handleEvent(StyledText.java:5663)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4454)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1388)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1412)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1397)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1424)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:824)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3293)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:769)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2098)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:5534)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4668)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9106)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1253)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2477)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3407)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.AbstractDocument.addPosition(AbstractDocument.java:355)
	at org.eclipse.core.internal.filebuffers.SynchronizableDocument.addPosition(SynchronizableDocument.java:236)
	at org.eclipse.jface.text.AbstractDocument.addPosition(AbstractDocument.java:376)
	at net.sourceforge.vrapper.eclipse.platform.EclipseCursorAndSelection.setMark(EclipseCursorAndSelection.java:518)
	... 58 more
~~~~

I do not hit the bug if:
* the "  }" is not on the last line, or
* if there's no space before "}".

**Comment by albertdev** [comment]
I can't immediately reproduce this...

Since whitespace is important, could you do `:set list` and make a (clipped) screenshot of the end of your file? Since it should only show a `}` and the surrounding whitespace, I believe there's no confidentiality issue.

I also wonder where the extra whitespaces on the new line come from. When I reproduce it, my cursor jumps to a new and empty line. Do you have some special formatter settings or do you have some Vrapper options like `softtabs` enabled?

**Comment by smelc** [comment]
Here's the initial position:

![vrapper-eof-crash-initial](https://cloud.githubusercontent.com/assets/634720/8226129/2fbda426-159c-11e5-90e3-711246b99785.png)

Pressing 'o' goes to this state (cursor is aligned with the `}` in this example :-/, my report was on a larger file, maybe it explains the difference):

![vrapper-eof-crash-getting-closer](https://cloud.githubusercontent.com/assets/634720/8226023/52ee61ac-159b-11e5-887a-354a1fde438d.png)

And then the exception happens when pressing ESC.

I haven't touched Vrapper's configuration and I hit the bug when using Eclipse's default formatter for Java (`Eclipse [built-in]` profile in the Preferences). Note that I also have the bug when editing programs written in my company's own programming language, which is [xtext](https://eclipse.org/Xtext) based.

**Comment by albertdev** [comment]
Thanks for the screenshots!

I now see why I couldn't reproduce it: editing an incomplete class file will make Eclipse insert indentation on that last line whereas editing a complete one will just make a new empty line. I get the same stacktrace now, though it occurs even faster if you use spaces as indentation.

The underlying bug is that `'cleanindent'` and the editing marks `[` / `]` don't properly work together, this shouldn't be too hard to fix. If you need a quick workaround, try putting `set nocleanindent` in your `.vraperrc`, though it will change Vrapper's behaviour.

**Comment by albertdev** [comment]
This little fix will be included in the next unstable and release build. Thanks for using Vrapper!

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.57.20150620) which includes this fix.  Please give it a try and let us know if you run into any other issues.  Thanks!

**Comment by smelc** [comment]
I cannot reproduce the bug with version 0.57.20150620.

Vrapper developers> keep rocking!
