### ISSUE TITLE
Vrapper commands are not visible in dark theme

### ISSUE THREAD

**Issue by hrj** [vrapper/vrapper#680]
Everything works fine with the default Eclipse theme. But in one particular case things don't work:

Eclipse version: Mars.
Ubuntu version: 14.04
Vrapper version: 0.58.0
Change the theme to Dark.
Then change `Windows / Preferences / Text Editor / Appearance color options / Background Color` to any custom color.

... and :boom:, vrapper commands are not visible. That is, when I try to search with `/`, the keys I enter are not visible but the command bar is.

I suspect the foreground and background colors of that command bar become the same, rendering the contents invisible.

This is consistently reproducible here.

Let me know if you need any more details.

**Comment by keforbes** [comment]
Could you include a screenshot?  That usually helps for visual issues like this.  Thanks!

**Comment by hrj** [comment]
Sure:

![eclipse-mars-vrapper-dark](https://cloud.githubusercontent.com/assets/345879/9176464/19fa6a66-3fa9-11e5-94eb-0189bbafd680.png)

The invisible commands are hard to see :) in the screenshot. But there is a dark-bar above the scrollbar where the cursor blinks and moves, and the commands work. They are just not visible.

**Comment by hrj** [comment]
One thing I noticed just now: Newly opened editors don't have this problem. Only the stale editors (which were already open when the preference was changed) have it.

**Comment by keforbes** [comment]
So if you close Eclipse and relaunch it the entire problem goes away?

**Comment by hrj** [comment]
Yup; until the next color change :)

**Comment by albertdev** [comment]
Ah, I believe we cache the command line widget for each editor until the whole editor is garbage collected.

Maybe we could reset the colors each time we hide and show the widget. AFAIK the `Color` instances are tied to the editor and should hence be garbage collected at some later point.

**Comment by albertdev** [comment]
I think I've got this fixed but I'm going to do some more testing.

I can't reproduce the invisibility problem on Windows (must be something with how Ubuntu's GTK version applies the styling to the widget tree) but I did get this when opening the command line in a stale editor:

```
!ENTRY org.eclipse.ui 4 0 2015-08-11 07:52:49.516
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.IllegalArgumentException: Argument not valid)
	at org.eclipse.swt.SWT.error(SWT.java:4491)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:138)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
Caused by: java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4472)
	at org.eclipse.swt.SWT.error(SWT.java:4406)
	at org.eclipse.swt.SWT.error(SWT.java:4377)
	at org.eclipse.swt.graphics.GC.setBackground(GC.java:4195)
	at org.eclipse.swt.custom.StyledTextRenderer.drawLine(StyledTextRenderer.java:371)
	at org.eclipse.swt.custom.StyledText.handlePaint(StyledText.java:6142)
	at org.eclipse.swt.custom.StyledText$7.handleEvent(StyledText.java:5688)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1137)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1122)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1512)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4719)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:339)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5050)
	at org.eclipse.swt.internal.win32.OS.RedrawWindow(Native Method)
	at org.eclipse.swt.widgets.Control.update(Control.java:4485)
	at org.eclipse.swt.widgets.Control.update(Control.java:4475)
	at net.sourceforge.vrapper.eclipse.ui.CommandLineUIFactory$TextEditorPaintListener$1.run(CommandLineUIFactory.java:132)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	... 23 more
```

Looks like this needed to be fixed anyhow...

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.59.20150815) which includes this fix.  Please give it a try and let us know if you're still having problems.  Thanks!
