### ISSUE TITLE
Cannot escape search

### ISSUE THREAD

**Issue by jzhong92** [vrapper/vrapper#691]
Upon pressing / , the first key pressed is always missing. Subsequent keys do not affect the editor, but updates the search criteria (e.g. /garbageinput). You can press Enter, but it will never exit SEARCH mode and you can't type as if in insert mode either. Esc doesn't do anything past the initial / for search mode.

**Comment by albertdev** [comment]
Can you check your Eclipse error log and see if there are any Vrapper-related errors in there? You can do so by opening the "Error log" view and then clicking the small "Open Log" button at the top right of that little view.

What OS and Eclipse version are you using?

**Comment by jzhong92** [comment]
Taken by exporting log. Windows 7 Enterprise and Eclipse Java EE IDE (4.4.2)


!ENTRY org.eclipse.ui 4 0 2015-10-13 06:18:20.037
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4441)
	at org.eclipse.swt.SWT.error(SWT.java:4356)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:139)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4147)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3764)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
Caused by: java.lang.NullPointerException
	at text.overview.views.OverviewView.addListenersLastOverviewedStyledText(OverviewView.java:453)
	at text.overview.views.OverviewView.trackStyledText(OverviewView.java:403)
	at text.overview.views.OverviewView.handleEvent(OverviewView.java:371)
	at text.overview.views.OverviewView$6.handleEvent(OverviewView.java:194)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1262)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1085)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2841)
	at org.eclipse.swt.widgets.Widget.wmSetFocus(Widget.java:2425)
	at org.eclipse.swt.widgets.Control.WM_SETFOCUS(Control.java:5236)
	at org.eclipse.swt.widgets.Canvas.WM_SETFOCUS(Canvas.java:456)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4680)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:339)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5023)
	at org.eclipse.swt.internal.win32.OS.SetFocus(Native Method)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:1097)
	at org.eclipse.swt.widgets.Control.setFocus(Control.java:3322)
	at org.eclipse.swt.widgets.Composite.setFocus(Composite.java:1041)
	at net.sourceforge.vrapper.eclipse.ui.EclipseCommandLineUI$5.run(EclipseCommandLineUI.java:193)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	... 23 more

!ENTRY org.eclipse.ui 4 0 2015-10-13 06:18:22.401
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at text.overview.views.OverviewView.removeListenersLastOverviewedStyledText(OverviewView.java:443)
	at text.overview.views.OverviewView.blank(OverviewView.java:458)
	at text.overview.views.OverviewView.access$0(OverviewView.java:457)
	at text.overview.views.OverviewView$1.textChanging(OverviewView.java:112)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:76)
	at org.eclipse.swt.custom.DefaultContent.sendTextEvent(DefaultContent.java:797)
	at org.eclipse.swt.custom.DefaultContent.replaceTextRange(DefaultContent.java:781)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7268)
	at org.eclipse.swt.custom.StyledText.replaceTextRange(StyledText.java:7870)
	at org.eclipse.swt.custom.StyledText.insert(StyledText.java:5498)
	at net.sourceforge.vrapper.eclipse.ui.EclipseCommandLineUI.type(EclipseCommandLineUI.java:166)
	at net.sourceforge.vrapper.vim.modes.commandline.AbstractCommandParser.type(AbstractCommandParser.java:174)
	at net.sourceforge.vrapper.vim.modes.commandline.AbstractCommandLineMode.handleKey(AbstractCommandLineMode.java:56)
	at net.sourceforge.vrapper.vim.modes.commandline.SearchMode.handleKey(SearchMode.java:121)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey0(DefaultEditorAdaptor.java:677)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:404)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey(DefaultEditorAdaptor.java:399)
	at net.sourceforge.vrapper.eclipse.interceptor.VimInputInterceptorFactory$VimInputInterceptor.verifyKey(VimInputInterceptorFactory.java:268)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:66)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1085)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1070)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:782)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:5981)
	at org.eclipse.swt.custom.StyledText$7.handleEvent(StyledText.java:5663)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1085)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1070)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1112)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1108)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1529)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4722)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:343)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4610)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:339)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5023)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2549)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

!ENTRY org.eclipse.ui 4 0 2015-10-13 06:18:24.117
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at text.overview.views.OverviewView.removeListenersLastOverviewedStyledText(OverviewView.java:443)
	at text.overview.views.OverviewView.trackStyledText(OverviewView.java:398)
	at text.overview.views.OverviewView.handleEvent(OverviewView.java:371)
	at text.overview.views.OverviewView$6.handleEvent(OverviewView.java:194)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1262)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1085)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:2841)
	at org.eclipse.swt.widgets.Widget.wmSetFocus(Widget.java:2425)
	at org.eclipse.swt.widgets.Control.WM_SETFOCUS(Control.java:5236)
	at org.eclipse.swt.widgets.Canvas.WM_SETFOCUS(Canvas.java:456)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4680)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:339)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5023)
	at org.eclipse.swt.internal.win32.OS.ShowWindow(Native Method)
	at org.eclipse.swt.widgets.Control.showWidget(Control.java:2821)
	at org.eclipse.swt.widgets.Control.setVisible(Control.java:3811)
	at net.sourceforge.vrapper.eclipse.ui.EclipseCommandLineUI.close(EclipseCommandLineUI.java:217)
	at net.sourceforge.vrapper.vim.modes.commandline.AbstractCommandLineMode.leaveMode(AbstractCommandLineMode.java:52)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.changeMode(DefaultEditorAdaptor.java:373)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.changeModeSafely(DefaultEditorAdaptor.java:218)
	at net.sourceforge.vrapper.vim.modes.commandline.SearchCommandParser.handleExit(SearchCommandParser.java:49)
	at net.sourceforge.vrapper.vim.modes.commandline.AbstractCommandParser.type(AbstractCommandParser.java:194)
	at net.sourceforge.vrapper.vim.modes.commandline.AbstractCommandLineMode.handleKey(AbstractCommandLineMode.java:56)
	at net.sourceforge.vrapper.vim.modes.commandline.SearchMode.handleKey(SearchMode.java:121)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey0(DefaultEditorAdaptor.java:677)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:404)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey(DefaultEditorAdaptor.java:399)
	at net.sourceforge.vrapper.eclipse.interceptor.VimInputInterceptorFactory$VimInputInterceptor.verifyKey(VimInputInterceptorFactory.java:268)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:66)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1085)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1070)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:782)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:5981)
	at org.eclipse.swt.custom.StyledText$7.handleEvent(StyledText.java:5663)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1085)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1070)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1112)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1108)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1529)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4722)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:343)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4610)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:339)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5023)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2549)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3759)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)

**Comment by albertdev** [comment]
@jzhong92 
Thanks for that. It looks like the [Overview plugin for Eclipse](https://marketplace.eclipse.org/content/overview-plugin-eclipse) doesn't like our command line window because it doesn't have a scrollbar.

When it crashes, it leaves its internal state inconsistent and blocks Vrapper from closing or resetting the command line window.

I've quickly checked out the code of that plugin, it seems it crashes in one of two spots.
Line 443: 
```
			((Scrollable) lastOverviewedStyledText).getVerticalBar().addSelectionListener(lastOverviewedStyledTextScrollBarSelectionListener);
```
and line 453:

```
			((Scrollable) lastOverviewedStyledText).getVerticalBar().removeSelectionListener(lastOverviewedStyledTextScrollBarSelectionListener);
```

The scrollbar doesn't exist so the `getVerticalBar()` property returns null, hence the Overview plugin crashes.

I've found that the plugin was hosted on Google-code but the project has frozen and the [issue ticket with a request to move to Github[(https://code.google.com/p/sandipchitaleseclipseplugins/issues/detail?id=16) was left unanswered.

I've seen that people on the [Overview plugin's marketplace page](https://marketplace.eclipse.org/content/overview-plugin-eclipse) have left comments about other crashes, maybe you can try to contact the author that way?

I can't help you any further short of fixing that third-party plugin. I don't know if the author would like it though and I don't have the ambition of maintaining it so I'm afraid you are on your own.

**Comment by albertdev** [comment]
It only now hit me that I could add a vertical scroll bar to improve going through a long message, e.g. the output of the `:ls` command. This would at least solve your immediate problem.

You should still warn the author of this bug though or your Eclipse might lock up in other funny ways.

**Comment by jzhong92** [comment]
Awesome, I let the author of the plugin know of this bug.

**Comment by albertdev** [comment]
The fix I described will be in the next release and unstable build. I've tested the plugin and it works now, though it did raise some other obscure errors which might be related to my test environment.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.61.20151020) which includes this fix.  Please test it out and let us know if there are any other problems.  Thanks!
