### ISSUE TITLE
NPE being thrown upon editor selection

### ISSUE THREAD

**Issue by mrietveld** [vrapper/vrapper#720]
When I change tabs/edtiors, I get the error message: 

```
An error has occurred. See error log for more details

java.lang.NullPointerException
````

I'm using: 

- Eclipse: Mars.1 Release (4.5.1)[Build id: 20150924-1200]
- Vrapper: 0.64.0
- Java 1.8.0_72

The following stack trace can then be found in the logs:
````
!ENTRY org.eclipse.ui.workbench 4 2 2016-02-02 17:44:24.259
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0
java.lang.NullPointerException
	at net.sourceforge.vrapper.eclipse.platform.EclipseBufferAndTabService.setCurrentEditor(EclipseBufferAndTabService.java:98)
	at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.partActivated(InputInterceptorManager.java:325)
	at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.partActivated(InputInterceptorManager.java:352)
	at org.eclipse.ui.internal.PartService$6.run(PartService.java:149)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.PartService.partActivated(PartService.java:146)
	at org.eclipse.ui.internal.WorkbenchPage$15.run(WorkbenchPage.java:4894)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4891)
	at org.eclipse.ui.internal.WorkbenchPage.access$19(WorkbenchPage.java:4870)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:202)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:245)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:242)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:711)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:639)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:634)
	at org.eclipse.ui.internal.WorkbenchPage.activate(WorkbenchPage.java:979)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3195)
	at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3149)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3131)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3126)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3090)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3071)
	at org.eclipse.ui.ide.IDE.openEditorOnFileStore(IDE.java:1159)
	at org.eclipse.ui.internal.views.log.OpenIDELogFileAction.run(OpenIDELogFileAction.java:42)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1329)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
````

**Comment by mrietveld** [comment]
It's driving me a little crazy to be getting this whenever I switch tabs.. :/

**Comment by albertdev** [comment]
Ugh, that's nasty. Do you know what kind of editor did you have open at the time you switched? Could it be some plugin (e.g. a database or server view) or an unsaved file?

I guess this isn't too hard to fix, but I'd like to know so that I can try to reproduce it before and after.

**Comment by mrietveld** [comment]
I was switching between Java editors -- IIRC, it didn't matter if the classes were in different projects or not.

**Comment by mrietveld** [comment]
Hmm. :/ I downgraded to 0.62.0 and I'm still running into the same issue -- although it does not immediately appear. 

I have a really weird suspicion that it's caused by some sort of weird interaction with the the [protocol buffer plugin](https://code.google.com/p/protobuf-dt/) that I have installed. 8|

**Comment by albertdev** [comment]
That plugin might do things which Vrapper didn't expect by closing its current input when switching away from it. It's still a bug in Vrapper when the code doesn't check for `null`.

I would recommend switching back to 0.64.0 though as this version fixed a critical flaw in some painting code, and not too much other stuff changed in the last few versions that it could impact this issue.

**Comment by albertdev** [comment]
I've tried to change the code so that it no longer assumes that any previous editors still keep their input file around after putting them in the background. While I was there, I also changed to code to use weak references so that Eclipse can garbage collect editors if it wants to.

This fix will be included in the next release and unstable build.

**Comment by keforbes** [comment]
I've updated the unstable update site with a new build (0.65.20160203) which includes this fix.  Please give it a try and let us know if you have any other problems.  Thanks!

**Comment by mrietveld** [comment]
@keforbes @albertdev AWESOME! Thanks, I'll try it ASAP and let you know.

**Comment by mrietveld** [comment]
Thank you again for fixing this so quickly: so far, 0.65 has not caused any problems for me. As far as I'm concerned, this problem has been fixed. 

Thanks again!
