### ISSUE TITLE
VrapperPlatformException: Failed to delete position category

### ISSUE THREAD

**Issue by sschaef** [vrapper/vrapper#730]
Sometimes I get errors like this one:
```
net.sourceforge.vrapper.platform.VrapperPlatformException: Failed to delete position category
	at net.sourceforge.vrapper.eclipse.platform.EclipseCursorAndSelection.uninstallHooks(EclipseCursorAndSelection.java:141)
	at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.partClosed(InputInterceptorManager.java:239)
	at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.partInputChanged(InputInterceptorManager.java:403)
	at org.eclipse.ui.internal.PartService$13.run(PartService.java:240)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.PartService.partInputChanged(PartService.java:237)
	at org.eclipse.ui.internal.WorkbenchPage$28.run(WorkbenchPage.java:5151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.WorkbenchPage.firePartInputChanged(WorkbenchPage.java:5148)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart$4.propertyChanged(CompatibilityPart.java:369)
	at org.eclipse.ui.part.WorkbenchPart.firePropertyChange(WorkbenchPart.java:132)
	at org.eclipse.ui.texteditor.AbstractTextEditor.firePropertyChange(AbstractTextEditor.java:6387)
	at org.eclipse.ui.texteditor.AbstractTextEditor.setInputWithNotify(AbstractTextEditor.java:4305)
	at org.eclipse.ui.texteditor.AbstractTextEditor.setInput(AbstractTextEditor.java:4319)
	at org.eclipse.ui.internal.WorkbenchPage.reuseEditor(WorkbenchPage.java:3037)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility.openEditor(SourceLookupFacility.java:477)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility.display(SourceLookupFacility.java:416)
	at org.eclipse.debug.internal.ui.sourcelookup.SourceLookupFacility$SourceDisplayJob.runInUIThread(SourceLookupFacility.java:785)
	at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:97)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3774)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3412)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

I think it only happens when I'm in the debugger and often switch between files by selecting different debugger frames. But I can't say for sure that this is the origin. It only happens in some rare cases but the result is that the editor is broken (it doesn't show any text anymore) and I have to close and reopen it.

**Comment by albertdev** [comment]
I think I've seen this stack-trace before, I'll have to check how easy it is to reproduce but I think I see where it is going wrong.

**Comment by albertdev** [comment]
I found a non-fatal way to reproduce it:

* Right-click in a Java file and use `References > Workspace`.
* The search view opens. Click the yellow down arrow with tooltip "Show next match"
* The Error Log view will be activated (if it was already open), it shows that a similar error occurred. 

In my case it's only an annoyance as I can just close the Error Log view and find the next match, it's just that it happens more often than I thought.
