### ISSUE TITLE
Error when enabling replace mode

### ISSUE THREAD

**Issue by dgbustos** [vrapper/vrapper#760]
Exiting replace mode (command `R`) causes the carrot to disappear and prevents me from closing the file.  The log indicates there is also an error on entering replace mode.  See [vrapper-replace-bug-log-20160815.txt](https://github.com/vrapper/vrapper/files/419270/vrapper-replace-bug-log-20160815.txt) .  Eclipse 4.6.0, Vrapper 0.68.1, Windows 10.

**Comment by keforbes** [comment]
Here are the relevant errors from that log file...
```
!ENTRY net.sourceforge.vrapper.eclipse 4 0 2016-08-15 20:32:42.023
!MESSAGE error when enabling replace mode
!STACK 0
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.sourceforge.vrapper.eclipse.platform.AbstractTextEditorSettings.setReplaceMode(AbstractTextEditorSettings.java:46)
	at net.sourceforge.vrapper.vim.modes.ReplaceMode.leaveMode(ReplaceMode.java:58)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.changeMode(DefaultEditorAdaptor.java:389)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.changeModeSafely(DefaultEditorAdaptor.java:229)
	at net.sourceforge.vrapper.vim.modes.InsertMode.handleKey(InsertMode.java:344)
	at net.sourceforge.vrapper.vim.modes.ReplaceMode.handleKey(ReplaceMode.java:131)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey0(DefaultEditorAdaptor.java:799)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:460)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey(DefaultEditorAdaptor.java:435)
```

```
!ENTRY net.sourceforge.vrapper.eclipse 4 0 2016-08-15 20:32:42.032
!MESSAGE unexpected exception when changing mode
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:354)
	at org.eclipse.swt.widgets.Caret.setBounds(Caret.java:382)
	at org.eclipse.swt.custom.StyledText.setCaretLocation(StyledText.java:8640)
	at org.eclipse.swt.custom.StyledText.setCaretLocation(StyledText.java:8614)
	at org.eclipse.swt.custom.StyledText.setSelectionRange(StyledText.java:9802)
	at org.eclipse.swt.custom.StyledText.setSelection(StyledText.java:9702)
	at org.eclipse.swt.custom.StyledText.setSelection(StyledText.java:9597)
	at net.sourceforge.vrapper.eclipse.platform.EclipseCursorAndSelection.setPosition(EclipseCursorAndSelection.java:186)
	at net.sourceforge.vrapper.vim.commands.MotionCommand.gotoAndChangeViewPort(MotionCommand.java:82)
	at net.sourceforge.vrapper.vim.commands.MotionCommand.doIt(MotionCommand.java:46)
	at net.sourceforge.vrapper.vim.modes.InsertMode.leaveMode(InsertMode.java:203)
	at net.sourceforge.vrapper.vim.modes.ReplaceMode.leaveMode(ReplaceMode.java:60)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.changeMode(DefaultEditorAdaptor.java:389)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.changeModeSafely(DefaultEditorAdaptor.java:229)
	at net.sourceforge.vrapper.vim.modes.InsertMode.handleKey(InsertMode.java:344)
	at net.sourceforge.vrapper.vim.modes.ReplaceMode.handleKey(ReplaceMode.java:131)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey0(DefaultEditorAdaptor.java:799)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:460)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey(DefaultEditorAdaptor.java:435)
	at net.sourceforge.vrapper.eclipse.interceptor.VimInputInterceptorFactory$VimInputInterceptor.verifyKey(VimInputInterceptorFactory.java:290)
```
@albertdev, any idea why the widget would be disposed already?

**Comment by albertdev** [comment]
@dgbustos Were there any errors earlier in the log file?

How often do you encounter this?

 What kind of projects were you editing, and what kind of Eclipse flavor or extra plugins do you have?

---

@keforbes I have just tried to reproduce the problem with Eclipse Neon and Vrapper 0.68.1 but I couldn't immediately do so.

It appears entering the mode was also broken due to that disposed caret widget:

```
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4514)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Canvas.setCaret(Canvas.java:308)
	at org.eclipse.swt.custom.StyledText.setCaret(StyledText.java:8570)
	at org.eclipse.ui.texteditor.AbstractTextEditor.updateCaret(AbstractTextEditor.java:6584)
	at org.eclipse.ui.texteditor.AbstractTextEditor.handleInsertModeChanged(AbstractTextEditor.java:6607)
	at org.eclipse.ui.texteditor.AbstractTextEditor.toggleOverwriteMode(AbstractTextEditor.java:6442)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.sourceforge.vrapper.eclipse.platform.AbstractTextEditorSettings.setReplaceMode(AbstractTextEditorSettings.java:46)
	at net.sourceforge.vrapper.vim.modes.ReplaceMode.enterMode(ReplaceMode.java:53)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.changeMode(DefaultEditorAdaptor.java:394)
	at net.sourceforge.vrapper.vim.modes.ReplaceMode$ChangeToReplaceModeCommand.execute(ReplaceMode.java:152)
	at net.sourceforge.vrapper.vim.commands.CountAwareCommand.execute(CountAwareCommand.java:16)
	at net.sourceforge.vrapper.vim.modes.CommandBasedMode.executeCommand(CommandBasedMode.java:262)
	at net.sourceforge.vrapper.vim.modes.CommandBasedMode.handleKey(CommandBasedMode.java:316)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey0(DefaultEditorAdaptor.java:799)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:460)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey(DefaultEditorAdaptor.java:435)
	at net.sourceforge.vrapper.eclipse.interceptor.VimInputInterceptorFactory$VimInputInterceptor.verifyKey(VimInputInterceptorFactory.java:290)
```

I don't know yet how this could occur...

**Comment by dgbustos** [comment]
I don't think there were other errors in the log file.  This happens every time for me.  I usually edit Java projects.  I think the plugins I use are typical, such as Maven and Git.

**Comment by albertdev** [comment]
*Sigh*, I couldn't reproduce it so far. I've done some quick tests editing Java files, XML or HTML but none of the editors would raise the error you've shown here.

**Comment by albertdev** [comment]
@dgbustos 
Would you be willing to create a few [gists](https://gist.github.com/) to share some more information about your setup?

First thing I'd like is your `.vrapperrc`.

Second thing is some diagnostic information from Eclipse. You can get it by going to Help > About Eclipse, then clicking on the Installation Details button. Once you get that screen open you should go to the last tab named `Configuration` and copy the contents of that tab into a gist.

**Comment by dgbustos** [comment]
Yes.  No `.vrapperrc`.  Configuration at https://gist.github.com/dgbustos/26ecdb26b85362452ba27087a475e492 .

**Comment by dgbustos** [comment]
I think this is a bug in Eclipse, where switching to replace mode with the "Use custom caret" preference unchecked attempts to use a disposed `Caret`.  I think I unchecked it while trying to get a block cursor before installing Vrapper.  When I disable Vrapper and hit my `INS` button with that preference unchecked, Eclipse logs an exception caused by

```
Caused by: java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4514)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:482)
	at org.eclipse.swt.widgets.Canvas.setCaret(Canvas.java:308)
	at org.eclipse.swt.custom.StyledText.setCaret(StyledText.java:8570)
	at org.eclipse.ui.texteditor.AbstractTextEditor.updateCaret(AbstractTextEditor.java:6584)
	at org.eclipse.ui.texteditor.AbstractTextEditor.handleInsertModeChanged(AbstractTextEditor.java:6607)
	at org.eclipse.ui.texteditor.AbstractTextEditor.toggleOverwriteMode(AbstractTextEditor.java:6442)
	at org.eclipse.ui.texteditor.AbstractTextEditor.access$14(AbstractTextEditor.java:6438)
	at org.eclipse.ui.texteditor.AbstractTextEditor$ToggleOverwriteModeAction.run(AbstractTextEditor.java:1115)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:118)
	... 56 more
```

If this makes sense, please advise where to file a bug for Eclipse.

**Comment by albertdev** [comment]
@dgbustos Thanks for the update, I'll try to reproduce the problem that way. It's still possible that we're doing something Eclipse doesn't suspect so I'd like to keep this issue around.

Does it still crash if you leave that option enabled (what I think is the default setting)?

**Comment by dgbustos** [comment]
After enabling the option, I have seen no problems and have been able to use `R`.
