### ISSUE TITLE
Vrapper and neon.1 are unhappy?

### ISSUE THREAD

**Issue by dgibson66** [vrapper/vrapper#765]
After I upgraded to neon.1 I started seeing this.  Am I alone?

!ENTRY net.sourceforge.vrapper.eclipse 4 0 2016-10-19 16:15:09.999
!MESSAGE Exception when intercepting AbstractTextEditor
!STACK 0
java.lang.NullPointerException
        at net.sourceforge.vrapper.eclipse.platform.EclipseTextContent$ModelSideTextContent.getNumberOfLines(EclipseTextContent.java:68)
        at net.sourceforge.vrapper.utils.UnmodifiableTextContentDecorator.getNumberOfLines(UnmodifiableTextContentDecorator.java:50)
        at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.setNewLineFromFirstLine(DefaultEditorAdaptor.java:240)
        at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.<init>(DefaultEditorAdaptor.java:165)
        at net.sourceforge.vrapper.eclipse.interceptor.VimInputInterceptorFactory.createInterceptor(VimInputInterceptorFactory.java:209)
        at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.interceptAbstractTextEditor(InputInterceptorManager.java:192)

**Comment by albertdev** [comment]
Ah, it's not supposed to do that.

What kind of editor did you have open?

**Comment by dgibson66** [comment]
Vrapper was the canary in the coalmine, I think.  There's a lot more going on here that's not Vrapper related.  Let's just close this at this point.
