### ISSUE TITLE
whenever typed '/' ':' keys, Unhandled event loop exception errors occurred

### ISSUE THREAD

**Issue by Yongho-John-Nam** [vrapper/vrapper#811]
eclipse: 4.8
Os: Ubuntu 18.04

```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4552)
	at org.eclipse.swt.SWT.error(SWT.java:4467)
	at org.eclipse.swt.SWT.error(SWT.java:4438)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:503)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:440)
	at org.eclipse.swt.custom.StyledText.getContent(StyledText.java:3745)
	at text.overview.views.OverviewView.removeListenersLastOverviewedStyledText(OverviewView.java:439)
	at text.overview.views.OverviewView.trackStyledText(OverviewView.java:398)
	at text.overview.views.OverviewView.handleEvent(OverviewView.java:371)
	at text.overview.views.OverviewView$6.handleEvent(OverviewView.java:194)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1721)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1369)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1396)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1375)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:4377)
	at org.eclipse.swt.widgets.Control.gtk_event_after(Control.java:3575)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1972)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6468)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5904)
	at org.eclipse.swt.internal.gtk.GTK._gtk_widget_grab_focus(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_widget_grab_focus(GTK.java:8859)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:2809)
	at org.eclipse.swt.widgets.Composite.forceFocus(Composite.java:636)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:2802)
	at org.eclipse.swt.widgets.Control.setFocus(Control.java:5105)
	at org.eclipse.swt.widgets.Composite.setFocus(Composite.java:1628)
	at org.eclipse.ui.texteditor.AbstractTextEditor.setFocus(AbstractTextEditor.java:6243)
	at org.eclipse.ui.texteditor.StatusTextEditor.setFocus(StatusTextEditor.java:144)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.delegateSetFocus(CompatibilityPart.java:222)
	at jdk.internal.reflect.GeneratedMethodAccessor62.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:324)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:246)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:136)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.focusGui(PartRenderingEngine.java:805)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:766)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:681)
	at org.eclipse.e4.ui.internal.workbench.swt.AbstractPartRenderer.activate(AbstractPartRenderer.java:94)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.lambda$0(ContributedPartRenderer.java:60)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5686)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1370)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1396)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1379)
	at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1862)
	at org.eclipse.swt.widgets.Control.gtk_button_press_event(Control.java:3450)
	at org.eclipse.swt.widgets.Control.gtk_button_press_event(Control.java:3370)
	at org.eclipse.swt.widgets.Composite.gtk_button_press_event(Composite.java:791)
	at org.eclipse.swt.widgets.Canvas.gtk_button_press_event(Canvas.java:156)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1965)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6468)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5904)
	at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4084)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1383)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1626)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4516)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
```

```
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4467)
	at org.eclipse.swt.SWT.error(SWT.java:4438)
	at org.eclipse.swt.custom.StyledText.setLineBackground(StyledText.java:9195)
	at text.overview.views.OverviewView.highlightViewport(OverviewView.java:500)
	at text.overview.views.OverviewView.trackStyledText(OverviewView.java:431)
	at text.overview.views.OverviewView.handleEvent(OverviewView.java:371)
	at text.overview.views.OverviewView$6.handleEvent(OverviewView.java:194)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1721)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1369)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1396)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1375)
	at org.eclipse.swt.widgets.Control.sendFocusEvent(Control.java:4377)
	at org.eclipse.swt.widgets.Control.gtk_event_after(Control.java:3575)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1972)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6468)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5904)
	at org.eclipse.swt.internal.gtk.GTK._gtk_widget_grab_focus(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_widget_grab_focus(GTK.java:8859)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:2809)
	at org.eclipse.swt.widgets.Composite.forceFocus(Composite.java:636)
	at org.eclipse.swt.widgets.Control.forceFocus(Control.java:2802)
	at org.eclipse.swt.widgets.Control.setFocus(Control.java:5105)
	at org.eclipse.swt.widgets.Composite.setFocus(Composite.java:1628)
	at net.sourceforge.vrapper.eclipse.ui.EclipseCommandLineUI$5.run(EclipseCommandLineUI.java:212)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4915)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4521)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
```

**Comment by Yongho-John-Nam** [comment]
And sometimes search or command line loses focus.

**Comment by albertdev** [comment]
What kind of file were you editing (so that I know if you are using specific plugins) or was it simply a `.java` file?

It looks like the stacktraces both pass through a third-party plugin:

```
	at text.overview.views.OverviewView.handleEvent(OverviewView.java:371)
```

Is it the [Overview plugin for Eclipse (Eclipse Marketplace)](https://marketplace.eclipse.org/content/overview-plugin-eclipse) you are using and can you specify the version?

Thanks for using Vrapper!

**Comment by Yongho-John-Nam** [comment]
overview plugin version : 1.0.30

I turned off Overview Plugin and the error didn't occurred anymore.
Thank you.

And I have 1 more error. '/' key typed 2 times, error occured.

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at net.sourceforge.vrapper.vim.modes.commandline.SearchCommandParser.getKeyWord(SearchCommandParser.java:126)
	at net.sourceforge.vrapper.vim.modes.commandline.SearchMode.doIncSearch(SearchMode.java:139)
	at net.sourceforge.vrapper.vim.modes.commandline.SearchMode.handleKey(SearchMode.java:127)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey0(DefaultEditorAdaptor.java:831)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:467)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey(DefaultEditorAdaptor.java:442)
	at net.sourceforge.vrapper.eclipse.interceptor.VimInputInterceptorFactory$VimInputInterceptor.verifyKey(VimInputInterceptorFactory.java:291)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:66)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5686)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1370)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1396)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1379)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1164)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6037)
	at org.eclipse.swt.custom.StyledText.lambda$1(StyledText.java:5740)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5686)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1370)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1396)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1379)
	at org.eclipse.swt.widgets.Widget.sendIMKeyEvent(Widget.java:1458)
	at org.eclipse.swt.widgets.Control.gtk_commit(Control.java:3472)
	at org.eclipse.swt.widgets.Canvas.gtk_commit(Canvas.java:165)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1967)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6468)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5904)
	at org.eclipse.swt.internal.gtk.GTK._gtk_im_context_filter_keypress(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_im_context_filter_keypress(GTK.java:3466)
	at org.eclipse.swt.widgets.Control.filterKey(Control.java:2678)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3731)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:842)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1986)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6468)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5904)
	at org.eclipse.swt.internal.gtk.GTK._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.GTK.gtk_main_do_event(GTK.java:4084)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1383)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:1626)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4516)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1471)
```

**Comment by keforbes** [comment]
> And I have 1 more error. '/' key typed 2 times, error occured.
```

**Comment by keforbes** [comment]
> And I have 1 more error. '/' key typed 2 times, error occurred.

```
java.lang.ArrayIndexOutOfBoundsException: 0
	at net.sourceforge.vrapper.vim.modes.commandline.SearchCommandParser.getKeyWord(SearchCommandParser.java:126)
	at net.sourceforge.vrapper.vim.modes.commandline.SearchMode.doIncSearch(SearchMode.java:139)
```

Just to be clear, this error is printed in the Error Log but there isn't any bad behavior, right?  I just tried this myself and if I didn't look at the Error Log I wouldn't have known this error was happening.

Why were you hitting `/` twice?

By the way, the error should go away if you disable incremental search `:set noincsearch` but I understand if you don't want to disable that feature.

**Comment by keforbes** [comment]
Nevermind.  The same issue happens without incremental search:
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at net.sourceforge.vrapper.vim.modes.commandline.SearchCommandParser.parseSearchCommand(SearchCommandParser.java:103)
	at net.sourceforge.vrapper.vim.modes.commandline.SearchCommandParser.parseAndExecute(SearchCommandParser.java:39)
	at net.sourceforge.vrapper.vim.modes.commandline.AbstractCommandParser.parseAndExecute(AbstractCommandParser.java:322)
	at net.sourceforge.vrapper.vim.modes.commandline.AbstractCommandParser.type(AbstractCommandParser.java:174)
```

Also, `//` should repeat the last search but instead when you hit enter it just goes to a newline in the command-line widget.

**Comment by keforbes** [comment]
Closing this issue so we can track the `//` issue in #812.
