### ISSUE TITLE
_vrapperrc

### ISSUE THREAD

**Issue by liveforday** [vrapper/vrapper#842]
I created the file named '_vrapperrc' manually  in the path `c:\Users\<username>`。 But it doesn't work,I doubt the config file '_vrapperrc'  is not be loaded correctly. How can i ensure the config be loaded correctly? 

* window10
* eslipse6

**Comment by keforbes** [comment]
Can you go to `Help -> About Eclipse IDE -> Installation Details -> Configuration -> View Error Log` and then see if you have this message towards the bottom of that file:
`!MESSAGE No .vrapperrc or _vrapperrc found.`
That will confirm whether Vrapper could find the file or not.  Note that if the file is found we also have some error logging for "Failed to parse .vrapperrc" and "Failed to execute command on line `x` of .vrapperrc" which could be helpful.

**Comment by liveforday** [comment]
thanks for your help. I don't find `!MESSAGE No .vrapperrc or _vrapperc found`. but I get this error log
```!ENTRY org.eclipse.equinox.p2.transport.ecf 2 0 2020-11-23 09:10:25.981
!MESSAGE Connection to http://vrapper.sourceforge.net/update-site/stable/p2.index failed on vrapper.sourceforge.net. Retry attempt 0 started
!STACK 0
java.net.UnknownHostException: vrapper.sourceforge.net
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1295)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1248)
	at java.net.InetAddress.getAllByName(InetAddress.java:1164)
	at java.net.InetAddress.getAllByName(InetAddress.java:1098)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:259)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.performConnect(HttpClientRetrieveFileTransfer.java:1077)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer.access$0(HttpClientRetrieveFileTransfer.java:1068)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientRetrieveFileTransfer$1.performFileTransfer(HttpClientRetrieveFileTransfer.java:1064)
	at org.eclipse.ecf.filetransfer.FileTransferJob.run(FileTransferJob.java:73)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.equinox.p2.transport.ecf 4 1006 2020-11-23 09:10:26.233
!MESSAGE Unknown Host: http://vrapper.sourceforge.net/update-site/stable/content.xml
!STACK 0
java.net.UnknownHostException: vrapper.sourceforge.net
	at java.net.InetAddress.getAllByName0(InetAddress.java:1252)
	at java.net.InetAddress.getAllByName(InetAddress.java:1164)
	at java.net.InetAddress.getAllByName(InetAddress.java:1098)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:259)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:259)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)```
I can use vrapper in my IDE normally with this error except config .vrapperrc. Is this error will causes `_vrapperrc` don't work

**Comment by keforbes** [comment]
Are there any messages in the eclipse error log with an `ENTRY` line like this?
```
!ENTRY net.sourceforge.vrapper.eclipse
```

Also, I should let you know the commands we support in vrapperrc are very minimal compared to what vimrc can do.  We support using `source .vimrc` so you can keep your .vrapperrc and .vimrc in sync but since .vimrc supports lots of crazy syntax we exclude a lot of it.  Vrapper will ignore anything within an `if` block, a `func` block, or a `try` block.  So if the contents of your .vrapperrc are within any of those blocks, vrapper is probably just ignoring it.

**Comment by liveforday** [comment]
there is no message like `!ENTRY net.sourceforge.vrapper.eclipse`. the configure file `_vrapperrc` is very simple. I just write `imap jj <Esc>`.

**Comment by keforbes** [comment]
Well in that case, I'm stumped.  If vrapper isn't throwing any errors then it must be reading your `_vrapperrc` correctly.  And I have `imap jk <esc>` in my `_vrapperrc` which works fine.

Can you try deleting (or renaming) your `_vrapperrc` to something else just to see if you get the "!MESSAGE No .vrapperrc or _vrapperrc found." error in your Eclipse error log?
