### ISSUE TITLE
:reg command doesn't work when used alone

### ISSUE THREAD

**Issue by codeRSH** [vrapper/vrapper#845]
Hi, 

When I use :reg command with an argument like **:reg "1** the command works :

![image](https://user-images.githubusercontent.com/4953198/126749347-5566d313-009b-4453-b8b6-965729d39aa0.png)

However, when using **:reg** command alone to see content of all registers,  the command doesn't doesn't work. 

![image](https://user-images.githubusercontent.com/4953198/126749433-43d8239f-c9b8-46aa-883c-0865c84a7b6d.png)

Am I missing something or this functionality is not implemented?

**Comment by keforbes** [comment]
`:reg` works fine for me, it brings up the list of all registers defined.  I'm guessing the problem has to do with the error in your second screenshot saying "error while changing to mode normal mode".

Can you check your Error Log for any errors related to Vrapper?  Go to Help -> About Eclipse IDE -> Installation Details -> Configuration tab -> View Error Log.  Scroll down to the bottom and see if you can find any errors with `net.sourceforge.vrapper` in them.

**Comment by codeRSH** [comment]
Hi, 

Thanks for the help. I am getting the following last error by following your path : 

`!ENTRY net.sourceforge.vrapper.eclipse 4 0 2021-07-26 14:14:03.340
!MESSAGE unexpected exception when changing mode
!STACK 0
java.lang.RuntimeException: Failed to switch to mode net.sourceforge.vrapper.vim.modes.NormalMode@5cc54c2b
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.changeMode(DefaultEditorAdaptor.java:430)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.changeModeSafely(DefaultEditorAdaptor.java:241)
	at net.sourceforge.vrapper.vim.modes.commandline.AbstractCommandParser.handleExit(AbstractCommandParser.java:306)
	at net.sourceforge.vrapper.vim.modes.commandline.AbstractCommandParser.type(AbstractCommandParser.java:207)
	at net.sourceforge.vrapper.vim.modes.commandline.AbstractCommandLineMode.handleKey(AbstractCommandLineMode.java:63)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey0(DefaultEditorAdaptor.java:832)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:467)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey(DefaultEditorAdaptor.java:442)
	at net.sourceforge.vrapper.eclipse.interceptor.VimInputInterceptorFactory$VimInputInterceptor.verifyKey(VimInputInterceptorFactory.java:354)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:70)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1067)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:766)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6101)
	at org.eclipse.swt.custom.StyledText.lambda$1(StyledText.java:5795)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4209)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1043)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1067)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1094)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1519)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4882)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:345)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4760)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4930)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3624)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:654)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1462)
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.core.runtime.IPath.makeAbsolute()" because the return value of "org.eclipse.core.resources.IFile.getRawLocation()" is null
	at net.sourceforge.vrapper.eclipse.platform.EclipseFileService.getCurrentFileLocation(EclipseFileService.java:693)
	at net.sourceforge.vrapper.eclipse.interceptor.VimInputInterceptorFactory$1.getContent(VimInputInterceptorFactory.java:98)
	at net.sourceforge.vrapper.vim.commands.ListRegistersCommand.getMessages(ListRegistersCommand.java:47)
	at net.sourceforge.vrapper.vim.commands.AbstractMessagesCommand.execute(AbstractMessagesCommand.java:17)
	at net.sourceforge.vrapper.vim.modes.commandline.CommandLineParser$9.evaluate(CommandLineParser.java:264)
	at net.sourceforge.vrapper.vim.modes.commandline.EvaluatorMapping.evaluate(EvaluatorMapping.java:33)
	at net.sourceforge.vrapper.vim.modes.commandline.CommandLineParser$RunEvaluatorCommand.execute(CommandLineParser.java:946)
	at net.sourceforge.vrapper.vim.modes.CommandBasedMode.executeCommand(CommandBasedMode.java:265)
	at net.sourceforge.vrapper.vim.modes.NormalMode.enterMode(NormalMode.java:325)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.changeMode(DefaultEditorAdaptor.java:401)
	... 53 more`
	
There was also an error of can't find _vrapperrc . So, I created a __vrapperrc file in my home directory in Windows and I think that error is now gone. But not sure what to make of this above error. Can you please help?

**Comment by keforbes** [comment]
So it looks like that error is caused by:
```
Cannot invoke "org.eclipse.core.runtime.IPath.makeAbsolute()" because the return value of "org.eclipse.core.resources.IFile.getRawLocation()" is null at net.sourceforge.vrapper.eclipse.platform.EclipseFileService.getCurrentFileLocation(EclipseFileService.java:693)
```

Was the file you were editing not saved yet or possibly deleted?  Can you open a file that is within a project Eclipse owns and then try `:reg` again?  One of the default registers Vrapper auto-populates is `"%`, which is the currently open file.  I'm guessing if Eclipse can't find the location of that file then the `:reg` command will fail.

**Comment by codeRSH** [comment]
Yes you are right!

Creating a 'local' project where the files reside in my system makes the `:reg` command work. 

However, I am an SAP developer, where my Eclipse connects to a remote Application system and fetches a cache of the program from the server on which I make edit and then save it back into the server. 

So, effectively I am not really working on a local file but a 'cache/buffer' of a remote file. 

Can there be a workaround/fix to make `:reg` work for my scenario as well? Since `:reg "1` works, so I assume there should be a way to make it work for `:reg` as well?

**Comment by keforbes** [comment]
> Can there be a workaround/fix to make :reg work for my scenario as well?

Sure.  I added a simple "return `""` if anything fails" block to that method so `"%` will just return an empty string in your scenario now.  I'm sorry I won't be able to determine your remote filename but at least the `:reg` command shouldn't fail anymore.

I've updated the unstable update site with this fix.  Please add the unstable update site (http://vrapper.sourceforge.net/update-site/unstable) to your Eclipse and then "Check for Updates" and it should find Vrapper 0.75.20210730, which includes this fix.  Please let me know if that works for you!

**Comment by codeRSH** [comment]
Hi, Thanks so much for the update. 

I would love to try out the fix, but I don't want to move to unstable branch (lest I may have to deal with other unknown issues). Any idea when this fix may move to stable branch?

**Comment by albertdev** [comment]
The way Vrapper development works is that we push changes to the unstable branch first. This would give us some time to run the version with all recent changes combined and lets the original bug reporter try changes without us having to cut an official release when a particular issue might not be fully resolved.

As a result, the stable branch is never updated until a set of changes is deemed stable enough, and we can't tell for sure if the reporter doesn't at least try it.

Of course, I can understand that you don't want to switch to the "unstable" update site, which would mean that your Eclipse might get yet another in-between version the next time you would click "Update plugins" in Eclipse. However, we've been neglecting to release a new stable version due to the sporadic changes over the last 3 years, so any changes in the unstable branch would thus flood into the stable branch anyway, so you could as well test it the way it is right now.

In the end it is your call, but you would be doing us a favor by reconfirming that the changes in there actually work outside of our development machines.

**Comment by codeRSH** [comment]
Hi, 

Sorry for late reply. 

Yes on switching to Unstable Branch, I am able to use :reg command even on my remote application server files. 
![image](https://user-images.githubusercontent.com/4953198/129141763-06556524-2073-4a48-a335-4d3e7474cf08.png)

Thanks for resolving this! Issue closed.
