### ISSUE TITLE
Cannot find active input interceptor for error editor

### ISSUE THREAD

**Issue by tivervac** [vrapper/vrapper#857]
As part of our product, Sigasi Studio, we have a talkback mechanism that automatically sends back errors that happen in the IDE. Passing this on to you as this is obviously where it belongs. I don't have much more context except that it likely happened in Sigasi Studio 4.17.1 which builds on Eclipse 2022-03

```
java.lang.Throwable: Failed to get mode 'net.sourceforge.vrapper.plugin.sneak.modes.SneakInputMode'

net.sourceforge.vrapper.vim.commands.CommandExecutionException:Failed to initialize InsertExpandMode.
    at net.sourceforge.vrapper.eclipse.modes.InsertExpandMode.<init>(InsertExpandMode.java:63)
    at net.sourceforge.vrapper.eclipse.modes.EclipseSpecificModeProvider.getModes(EclipseSpecificModeProvider.java:21)
    at net.sourceforge.vrapper.eclipse.mode.UnionModeProvider.getModes(UnionModeProvider.java:24)
    at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.getMode(DefaultEditorAdaptor.java:589)
    at net.sourceforge.vrapper.plugin.sneak.commands.utils.EditorAdaptorStateManager.getSneakState(EditorAdaptorStateManager.java:22)
    at net.sourceforge.vrapper.plugin.sneak.commands.utils.EditorAdaptorStateManager.markSneakInactive(EditorAdaptorStateManager.java:43)
    at net.sourceforge.vrapper.plugin.sneak.modes.SneakCommandListener.vrapperToggled(SneakCommandListener.java:43)
    at net.sourceforge.vrapper.vim.VrapperEventListeners.fireVrapperToggled(VrapperEventListeners.java:62)
    at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.onChangeEnabled(DefaultEditorAdaptor.java:853)
    at net.sourceforge.vrapper.eclipse.activator.VrapperPlugin.setVrapperEnabled(VrapperPlugin.java:231)
    at net.sourceforge.vrapper.eclipse.actions.VrapperToggleHandler.execute(VrapperToggleHandler.java:26)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
    at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
    at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
    at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
    at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
    at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
    at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:366)
    at net.sourceforge.vrapper.eclipse.activator.VrapperPlugin.toggleVrapper(VrapperPlugin.java:173)
    at net.sourceforge.vrapper.eclipse.activator.VrapperStartup$1.run(VrapperStartup.java:16)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4035)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3635)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
    at com.sigasi.runner.SigasiIDEApplication.start(SigasiIDEApplication.java:67)
    at com.sigasi.runner.SigasiRunner.main(SigasiRunner.java:268)
    at com.sigasi.runner.SigasiRunner.start(SigasiRunner.java:561)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

Caused by:
java.lang.Throwable: Caused by: net.sourceforge.vrapper.eclipse.interceptor.UnknownEditorException: Cannot find active input interceptor for editor org.eclipse.ui.internal.ErrorEditorPart@545e1a0e. Unknown sub-editor type org.eclipse.ui.internal.ErrorEditorPart@545e1a0e
    at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.findActiveInterceptor(InputInterceptorManager.java:746)
    at net.sourceforge.vrapper.eclipse.interceptor.InputInterceptorManager.findActiveInterceptor(InputInterceptorManager.java:723)
    at net.sourceforge.vrapper.eclipse.activator.VrapperPlugin.findActiveInterceptor(VrapperPlugin.java:79)
    at net.sourceforge.vrapper.eclipse.modes.InsertExpandMode.<init>(InsertExpandMode.java:56)
```

**Comment by keforbes** [comment]
Thanks for filing the issue, this is indeed the correct place.  However, with no steps to reproduce or symptoms of bad behavior, there's not much I can do.  It looks like the user tried activating the sneak plugin while the active editor was an ErrorEditorPart, which Vrapper doesn't know how to intercept the input from.
