### ISSUE TITLE
Using line-up / line-down causes unhandled event loop exceptions

### ISSUE THREAD

**Issue by albertdev** [vrapper/vrapper#875]
I'm trying a Vrapper built from `master` on Eclipse 2024-02 and traversing files seems to frequently trigger the following exception:

```
net.sourceforge.vrapper.platform.VrapperPlatformException: Failed to get line info for V-1
	at net.sourceforge.vrapper.eclipse.platform.EclipseTextContent$ViewSideTextContent.getLineInformationOfOffset(EclipseTextContent.java:143)
	at net.sourceforge.vrapper.utils.UnmodifiableTextContentDecorator.getLineInformationOfOffset(UnmodifiableTextContentDecorator.java:45)
	at net.sourceforge.vrapper.vim.commands.MotionCommand.gotoAndChangeViewPort(MotionCommand.java:68)
	at net.sourceforge.vrapper.vim.commands.MotionCommand.doIt(MotionCommand.java:52)
	at net.sourceforge.vrapper.vim.commands.MotionCommand.execute(MotionCommand.java:32)
	at net.sourceforge.vrapper.vim.commands.CountAwareCommand.execute(CountAwareCommand.java:16)
	at net.sourceforge.vrapper.vim.modes.CommandBasedMode.executeCommand(CommandBasedMode.java:299)
	at net.sourceforge.vrapper.vim.modes.CommandBasedMode.handleKey(CommandBasedMode.java:353)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey0(DefaultEditorAdaptor.java:832)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKeyOffRecord(DefaultEditorAdaptor.java:467)
	at net.sourceforge.vrapper.vim.DefaultEditorAdaptor.handleKey(DefaultEditorAdaptor.java:442)
	at net.sourceforge.vrapper.eclipse.interceptor.VimInputInterceptorFactory$VimInputInterceptor.verifyKey(VimInputInterceptorFactory.java:354)
	at org.eclipse.jface.text.TextViewer$VerifyKeyListenersManager.verifyKey(TextViewer.java:480)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:68)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:778)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:5742)
	at org.eclipse.swt.custom.StyledText.lambda$28(StyledText.java:5426)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4274)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1117)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1840)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:5153)
	at org.eclipse.swt.widgets.Canvas.WM_KEYDOWN(Canvas.java:406)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4776)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5039)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3658)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:639)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
Caused by: java.lang.IllegalArgumentException: Index out of bounds
	at org.eclipse.swt.SWT.error(SWT.java:4903)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.custom.StyledText.getLineAtOffset(StyledText.java:3590)
	at net.sourceforge.vrapper.eclipse.platform.EclipseTextContent$ViewSideTextContent.getLineInformationOfOffset(EclipseTextContent.java:141)
	... 57 more
```

So far I haven't investigated where it goes wrong, but it seems to happen when the line we're moving to is shorter than the current line.

**Comment by albertdev** [comment]
To be honest, this might be a bug related to High DPI screens. My Eclipse is also using tiny icons for some reason so maybe the situation will improve after a reboot.

**Comment by keforbes** [comment]
It's not just your HiDPI, I'm able to reproduce this error in my test Eclipse instance (running the latest code).  If I hit `jjjjjj` the cursor will start going down lines but then randomly start entering `jjjj` characters as I type (without moving into insert mode).  So we definitely need to figure this out.

**Comment by keforbes** [comment]
MotionCommand.java, line 68:
```
        LineInformation line = viewContent.getLineInformationOfOffset(pos.getViewOffset());
```
`pos.getViewOffset()` is returning `-1` for some reason.  But you're right, `h` and `l` work fine, it's only if `j` or `k` move to a line shorter than the current one.

**Comment by albertdev** [comment]
Found the issue: https://github.com/vrapper/vrapper/blob/master/plugins/net.sourceforge.vrapper.eclipse/src/net/sourceforge/vrapper/eclipse/platform/EclipseCursorAndSelection.java#L213 used to have the (deprecated) `getOffsetAtLocation()` function to find the character offset of the `stickyColumn` in a given line. This function threw an exception when the requested line doesn't have enough characters to calculate that offset,  and if so we wouldn't do an early return and calculate the last character in that line.

A recent commit by @frankbenoit replaced the deprecated function for the `getOffsetAtPoint()` function which is faster because it doesn't need to calculate an exception's stacktrace and returns `-1`. However, that means we will no longer end up in the `catch` block and fall through, hence we crash elsewhere due to the invalid offset.

I'll modify the code and try it out a little, then push the fixed code.
